### ISSUE TITLE
Spec2-wip.pdf "addFilm" method on page 16 : field names not correct

### ISSUE THREAD

**Issue by riVDM** [SquareBracketAssociates/BuildingApplicationWithSpec2#10]
Hi,
I think the field names in the method "addFilm" are not correct

In the book (section 2.8):

ImdbFilmListPresenter >> addFilm
| dialog windowPresenter |
dialog := ImdbFilmPresenter newApplication: self application.
windowPresenter := dialog openModalWithSpec.
windowPresenter isOk
ifFalse: [ ^ self ].
ImdbFilm
addFilm:
(ImdbFilm new
name: dialog **nameText** text;
director: dialog director text;
year: dialog **yearNumber** number).
self updatePresenter_

Should be:

...
(ImdbFilm new
name: dialog _**name**_ text;
director: dialog director text;
year: dialog **_year_** number).
...

For a reason i don't know, nameText is accepted but neither directorText nor yearNumber.

**Comment by riVDM** [comment]
This is a copy of the screen with "yearNumber" in red.
 
![image](https://user-images.githubusercontent.com/67067876/87168687-2996f800-c2cf-11ea-8eb5-c08657ef5c60.png)

**Comment by riVDM** [comment]
The field names do not seem logic to me, they should be "name","director" and "year" OR "nameText", "directorText" and "yearNumber" but not a mix of the two (between "dialog" and "text" or "number").
I tried to implement the example as described in the book but the dialog (film details) hangs up when i click on "Cancel" or "Save film".

**Comment by Ducasse** [comment]
replaced and fixed
