### ISSUE TITLE
 Figure ?? in Film tutorial

### ISSUE THREAD

**Issue by Ducasse** [SquareBracketAssociates/BuildingApplicationWithSpec2#108]
Now we can open the FilmListPresenter and click on the Add film but- ton. When the film data has been entered and the Save Film button has been clicked, you will see that the FilmListPresenter is updated with the added film, as shown in Figure ??

**Comment by koendehondt** [comment]
I see this, so I am not sure what the problem is:

<img width="789" alt="Screenshot 2024-06-16 at 15 15 45" src="https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/753271/9c2c4f97-dbe4-47e4-88ae-12a6425f6c2a">
