### ISSUE TITLE
iconManager: is mentioned but declared as "TOREMOVE" in Spec P13

### ISSUE THREAD

**Issue by astares** [SquareBracketAssociates/BuildingApplicationWithSpec2#112]
The book mentions #iconManager: in chapter 3.7 to set a custom icon manager - but this setter method
is in category "TOREMOVE" in Pharo 13 and there is no sender of the getter method #iconManager

**Comment by koendehondt** [comment]
Hi @astares,

Thank you for the feedback. However, in the latest builds of the PDF, I do not find `iconManager:` anymore. Could you tell us which version (i.e. date) of the PDF you have? You find the date on the page with the book title.

We are in the process of finalizing the book for Spec 2.0. A lot has changed or improved. We use Pharo 12 as the basis for the code examples and the explanation.

**Comment by astares** [comment]
@koendehondt 
- Situation for #iconManager getter/setter is the same in Pharo 12 and Pharo 13
- Date of books PDF build is from yesterday (**July 2, 2024**)

**Comment by astares** [comment]
Latest build PDF 

From https://objects.githubusercontent.com/github-production-release-asset-2e65be/187995713/de76b2ed-3439-4cd2-9107-2a16cdc5a293?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240703%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240703T135648Z&X-Amz-Expires=300&X-Amz-Signature=0f731c70c66ce1b4a49d031ff5efccfe724a09e1412b9d78e2231a44a1a9f8ac&X-Amz-SignedHeaders=host&actor_id=5980033&key_id=0&repo_id=187995713&response-content-disposition=attachment%3B%20filename%3DSpec2-wip.pdf&response-content-type=application%2Foctet-stream

**Comment by astares** [comment]
![image](https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/5980033/3b31a3df-8ccd-4ddc-8f08-27c094eacb6a)


![image](https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/5980033/79185f71-fe15-41ac-8ae3-ec8e79ca81f2)

**Comment by koendehondt** [comment]
I see it now. My PDF reader does not search well. I will take a look. Thanks.

**Comment by astares** [comment]
Having a symbol "iconManager" represented with a break as "icon-Manager" is also not very fortunate

**Comment by koendehondt** [comment]
The single reference to `iconManager:` has been replaced by `iconProvider`. See https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/commit/ed91b898f442457183ff2c3c3c80564b800f62cf

Thanks again for the feedback.
