### ISSUE TITLE
p228 ShowCcFieldShowBccFieldCommandommand

### ISSUE THREAD

**Issue by Ducasse** [SquareBracketAssociates/BuildingApplicationWithSpec2#120]
it looks like we got a little edit problem in the ShowBCCFieldCommand.

**Comment by koendehondt** [comment]
Could you be more specific? 🙂 What is the edit problem?

**Comment by koendehondt** [comment]
I see the issue. I fixed it in https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/commit/bb70070f58fe3fb3211e9a4a51a11eab90b900bc.
