### ISSUE TITLE
newToolBarButton not implemented SpPresenter

### ISSUE THREAD

**Issue by robkuz** [SquareBracketAssociates/BuildingApplicationWithSpec2#15]
Page 13 (Pharo 8)

**Comment by agiaccone** [comment]
in the code the selector is named newToolbarButton not newToolBarButton. Same thing with newToolBar, in the code the selector is named newToolbar

**Comment by Ducasse** [comment]
Thanks. The book is really is a super draft mode.
Sorry about it.
