### ISSUE TITLE
Use of Slots such as in 2.2 A basic film model fails

### ISSUE THREAD

**Issue by mldavis99** [SquareBracketAssociates/BuildingApplicationWithSpec2#21]
Object << #ImdbFilm
	**slots: {#name . #year . #director};**
	package: 'Spec2-TutorialOne'

The use of slots: instead of the conventional class template with instance variables results in errors saying that Object does not understand slots.  Using the conventional templating with instance variables works.  This is consistent throughout of the use of slots???  Also, the use of 

> #name . #year . #director

 as instance variables throws and error as well but works when non symbol variables are used.
In Pharo 10 64bit latest.
  NEVER MIND - I was finally pointed to the Fluid check box in the class editor on Discord.  However it would still be of value to explain this in the introduction until it becomes the default.

**Comment by Ducasse** [comment]
Works in P12.
