### ISSUE TITLE
Typo in SpMethodListerWithModel >> modelChanged on p. 54

### ISSUE THREAD

**Issue by LNUitTutor** [SquareBracketAssociates/BuildingApplicationWithSpec2#24]
Now the method is:

SpMethodListerWithModel >> modelChanged
list items: _aClass_ selectors sorted

It should be:
SpMethodListerWithModel >> modelChanged
     list items: **self model** selectors sorted

**Comment by Ducasse** [comment]
Thanks I will restart to work on the book in September.

**Comment by LNUitTutor** [comment]
Included into the issue #31
