### ISSUE TITLE
Comment to chapter 3 - continuation

### ISSUE THREAD

**Issue by LNUitTutor** [SquareBracketAssociates/BuildingApplicationWithSpec2#28]
p. 28: Testing. Method _FilmListPresenterTest >> setUp_ send message _ImdbFilm reset_ and destroyі all previously saved films. Why!?
Why don't we define the reset methods like this:
```
ImdbFilm >> reset
   copy := films.
   films := OrderedCollection new
ImdbFilm >> restore
   films := copy.
   copy := nil.
FilmListPresenterTest >> tearDown
   presenter ifNotNil: [ presenter delete ].
   ImdbFilm restore .
   super tearDown
```

p. 33: Typo in ImdbConfiguration >> customStyleSheet
```
^ '
.application [
.customLabel [ Draw { #color: #red } ] ] ')
```
The closing parenthesis should be removed.

**Comment by Ducasse** [comment]
checked and fixed.
