### ISSUE TITLE
Comment to chapter "Reuse and composition at work"

### ISSUE THREAD

**Issue by LNUitTutor** [SquareBracketAssociates/BuildingApplicationWithSpec2#32]
p. 61 Bug in the code: “WidgetClassListPresenter >> initializePresenters list := self newList. list items: (**AbstractWidgetModel** allSubclasses sorted: [:a :b | a name < b name ]). self focusOrder add: list.” – should be _SpAbstractWidgetPresenter_.

p. 61 “To allow this, we add a configuration method named whenSelectionChangedDo: as **follows:**” – it would be better ends the line with dot but colon.

p. 62 There is a contradiction (may be) in naming of ProtocolMethodListPresenter’s instance variables: “label” points to the kind of a widget, “methods” points to the way of using.

p. 62 Bugs in the code 

- “ProtocolMethodListPresenter >> initializePresenters methods := self newList. methods **displayBlock:** [ :m | m selector ]. …” – should be _display:_ [ :m | m selector ].
- “This UI can be seen by executing **ProtocolMethodList** new open.” – should be _ProtocolMethodListPresenter_.
- “ProtocolMethodListPresenter >> defaultLayout ^ SpBoxLayout newVertical add: #label withConstraints: [:c | c expand: false]; add: #methods withConstraints: [:c | c **fill**]; yourself” – should be c _fill: true_.

p. 64 Note “… the methods and the label are accessible through their **accessors**,” – but no any accessors were defined.

p. 67 Wrong name of class in the code snippet “**ProtocolViewer** new open” – should be _ProtocolViewerPresenter_.

Bad presentation: _ProtocolViewerPresenter_ with default extent shows only two included presenters: _models_ and _api_. The _events_ presenter is hidden below the bottom edge of the window. We can view the presenter only by dragging the bottom edge down. The situation is much more worse with the _horizontalLayout_: it is impossible to show the event presenter, even by dragging the right edge right.

p. 72 The explanation is not complete. Class _ProtocolCodeBrowserPresenter_ is not described.

**Comment by LNUitTutor** [comment]
![BadRepresentation](https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/37895159/2a074f78-5d6a-4d9a-a6c3-9e0a4fcb98b6)
An illustration to the "Bad presentation"

**Comment by Ducasse** [comment]
Checked all the points and addressed them
