### ISSUE TITLE
Comment to chapter 18 - Todo extracted Chapter

### ISSUE THREAD

**Issue by LNUitTutor** [SquareBracketAssociates/BuildingApplicationWithSpec2#42]
p. 178 “TodoTask class >> tasks ^ tasks ifNil: [ tasks := **OrderedCollection** new ]” – why an OrderedCollection? Why not a **Set**? The method _TodoTask class >> addTask: aTask_ checks _(tasks includes: aTask)_ to ensure uniqueness of a task.

p. 179
- “TodoTask new title: 'Task One'; save. TodoTask new title: 'Task Two'; save.” does not work because _tasks_ is nil. We need to perform “_TodoTask tasks_” first.
- “Compiled programs **have** like C **have** main()” – too much have 
- “TodoListPresenter >> initializePresenters **todoListPresenter** := self newTable …” – _todoListPresenter_ is undeclared. We have to add _slots: { #todoListPresenter }_ to the code snippet above.

p. 181
- “TodoApplication >> start **TodoListPresenter open**” – _new_ missing. It should be “_start TodoListPresenter new open_”. But is it a right way to connect the presenter with the application? May be “_(self newPresenter: TodoListPresenter) open_” would be better?
- “initializeWindow: aWindowPresenter” should be “**_TodoListPresenter >>_** initializeWindow: aWindowPresenter”

p. 184
- “TodoTaskPresenter >>accept **self** task title: titlePresenter text; save” – self is needless, should be removed.
- Question about responsibility. _TodoTaskPresenter_ is a helper dialog. Its duty is to get data from a user and to create (may be) an instance of _TodoTask_. Why does it save the task? Why does it change the data model? Is it a right responsibility for a helper dialog?

p. 186 Question. _TodoListPresenter >> addTask_ method opens new _TodoTaskPresenter_ dialog with the prompt '_Please give me a title_'. Is it possible to open the dialog with the prompt selected? It is quite noising to select the text every time.

p. 187 “TodoListPresenter >> defaultLayout ^ SpBoxLayout newTopToBottom spacing: 5; … add: (SpBoxLayout newLeftToRight addLast: **addButton** expand: false; yourself)” – _addButton_ is undeclared.
p. 188 “**addButton** := self newButton” – _addButton_ is undeclared.

p. 189
- “_TodoListPresenter >> todoListContextMenu ^ self newMenu_ …” commands of the menu work on an empty row of the table.
- Logical error: _TodoListPresenter >> editSelectedTask_ opens _TodoTaskPresenter_ with '_New task_' at the caption. How can I change it by '_Edit task_'?
- Error: “TodoListPresenter >> removeSelectedTask todoListPresenter selection selectedItem **remove**.” – should be _delete_. How about some confirmation?

Figures 18-4, 18-5 do not contain the row with “_Title_” at the top of the table.

**Comment by koendehondt** [comment]
This chapter is not part of the book anymore.
