### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by arnsholt** [SquareBracketAssociates/BuildingApplicationWithSpec2#46]
I've been working through the book, and I think I've found a couple of typos in the code:

`newToolbars` should be `newToolbar` in https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/blob/31ee2f7dfc5b58d53813435d2eddb9d7e0484724/Chapters/CaseStudyOne/CaseStudyOne.md?plain=1#L191

I think `presenter` is also referred to with `dialog` in https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/blob/31ee2f7dfc5b58d53813435d2eddb9d7e0484724/Chapters/CaseStudyOne/CaseStudyOne.md?plain=1#L357-L371

**Comment by Ducasse** [comment]
Thanks for the feedback!!!!
