### ISSUE TITLE
check glamourous

### ISSUE THREAD

**Issue by Ducasse** [SquareBracketAssociates/BuildingApplicationWithSpec2#69]
```
Chapters/Style/Style.md:    zoomInButton icon: (self iconNamed: #glamorousZoomIn).
Chapters/Style/Style.md:    zoomOutButton icon: (self iconNamed: #glamorousZoomOut).
```

**Comment by koendehondt** [comment]
The icons exist:

<img width="732" alt="Screenshot 2024-04-19 at 11 45 02" src="https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/753271/12d1d7b1-5156-470e-b275-2811311d32fd">

Please close if this solves your issue.

**Comment by koendehondt** [comment]
The real issue is to not use glamorous icons.
