### ISSUE TITLE
Finish chapter "Spec core in a nutshell"

### ISSUE THREAD

**Issue by koendehondt** [SquareBracketAssociates/BuildingApplicationWithSpec2#74]
Open issues from https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/pull/53:

- [x] The introduction and the first two paragraphs of the section "Spec core principle" are the same as in Chapter 1. I think we should take them out or rephrase them because the exact repetition is annoying for a reader who reads the book from front to back.
- [x] The last paragraph in the section "Spec core principle" states that `without modifying your UI described as presenters with Spec, you can render your application in the Pharo image with Morphic or as a native application with external Windows thanks to the Gtk backend.`. That is not correct. The stylesheets are different for the different backends.
- [x] The diagram in figure 5-1 "Architecture of Spec." is not correct. It expresses that every Presenter has exactly one Layout, but the second bullet in section 5.3 "Spec core architecture overview" states `at least one layout`.
- [x]  In the same diagram, there should be a "0..n" arrow from Layout to Presenter because layouts hold on to their presenters, for instance in the `children` instance variable of `SpExecutableLayout`. So we have a presenter tree.
- [x] In section 5.4 "Presenters" the term "model" is ambiguous. First, we have the sentence `It can be the model of a simple UI widget such as a button as well as of a complex UI widget composed by many other presenters (either simple or complex).` A bit further down the text, we have `A presenter may also have a model that is a domain object you need to interact with to display or update data.`. So we have a model that has a model. That is complicated. Can't we express the first sentence better?

Other:

- [x] Section "Layouts" includes a forward reference to `MyMiniBrowserPresenter` in the "Dynamic presenters" chapter. **This has to be fixed before the next two tasks**.
- [x] Use screenshots in Pharo Light theme.
- [x] The label "RightToLeft" in the figure in section "Layouts" should be "LeftToRight". Fixing this requires adapting the file `InANutshell/figures/layout6Annotated.graffle`.

**Comment by koendehondt** [comment]
PR: https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/pull/91

**Comment by koendehondt** [comment]
@Ducasse This chapter includes a forward reference to `MyMiniBrowserPresenter`, which is strange. I suggest using the Customer Satisfaction Survey window from the chapter "A 10 min small example". Readers already know it, so it is easy to revisit `#defaultLayout` in the section "Layouts" of this chapter.

**Comment by koendehondt** [comment]
@Ducasse My work is done. Please adapt the diagrams as we discussed and as described in the description of this PR.

**Comment by koendehondt** [comment]
This issue was closed automatically, but there are still two tasks to complete. Therefore reopen it.

**Comment by Ducasse** [comment]
I did the diagram and there are in the generated pdf so can you check?

**Comment by koendehondt** [comment]
> I did the diagram and there are in the generated pdf so can you check?

The diagrams are in the book :-) Thank you. We can close this issue. Another chapter done!
