### ISSUE TITLE
defaultLayout should be defaultSpec?

### ISSUE THREAD

**Issue by riVDM** [SquareBracketAssociates/BuildingApplicationWithSpec2#8]
Hi,
I follow the Spec2-wip.pdf doc and noticed that it uses "defaultLayout" :

_ImdbFilmListPresenter class >> defaultLayout
^ SpBoxLayout newVertical
add: #filmList;
yourself_

This generates an error.
But the ImdbFilmListPresenter class actually expects a "defaultSpec" method. I renamed defaultLayout in defaultSpec and it now runs OK.

Richard

**Comment by estebanlm** [comment]
mmm... that's a bug in Spec2, not in the book.
I will fix it asap. For the moment you can use defaultSpec instead, indeed.

**Comment by riVDM** [comment]
Thank you.

**Comment by riVDM** [comment]
I have a more general question. When i encounter some differences between the book and Spec2 or inconsistencies inside the book (well when i think having found some), do i have to create and publish a new issue each time or is there a more appropriate channel to report them? 
For example, the book contains this:

SpApplication subclass: #ImdbApp
instanceVariableNames: ''
classVariableNames: ''
package: 'Spec2-TutorialOne’

but later uses this as an example:

| app |
app := ImbdApplication new.
(app newPresenter: ImdbFilmListPresenter) openWithSpec.

which doesn’t work; i renamed ImbdApplication by ImdbApp and it’s OK (remark: the substring « Imdb » is used everywhere except in « ImbdApplication » which i see as an inconsistency).

Thank you,
Richard

**Comment by estebanlm** [comment]
Hi Richard, 

First, thank you a lot for taking the time to read/apply the book. Testing it is the only way to detect and fix problems. 
I think raising issue is a very good way to raise the problems (both on Spec book and Spec itself). 
If you need more quick answers, you can reach #spec channel on discord.
