### ISSUE TITLE
Finish chapter "Menu and MenuBar"

### ISSUE THREAD

**Issue by koendehondt** [SquareBracketAssociates/BuildingApplicationWithSpec2#81]
- [x] Add content

**Comment by koendehondt** [comment]
[Spec issue #1559](https://github.com/pharo-spec/Spec/issues/1559) is blocking the code examples in this chapter because we cannot disable toolbar buttons. The UI does not open.

When [#1559](https://github.com/pharo-spec/Spec/issues/1559) is fixed, [Spec issue #1560](https://github.com/pharo-spec/Spec/issues/1560) is confusing for the users because disabled toolbar buttons can be clicked and their action is triggered, which is highly undesirable.

@Ducasse It would be good to let these bugs be fixed before the book is released.

**Comment by Ducasse** [comment]
@estebanlm I added the tag forBookrelease so that we can sync with you.

**Comment by koendehondt** [comment]
@Ducasse

Here is a screenshot of the small application I like to use in this chapter. I write "small", but there is quite some code involved.

All the aspects are there: menubar, toolbar, status bar (no text in the status bar in the screenshot), context menu. Because all these aspects will be described in the chapter, I would like to change the chapter title to "Menubar, Toolbar, Status bar and Context Menus. wdyt?

There are still a few questions open in mail and in Github issues. When they are resolved, I can start writing the text of the chapter.

<img width="650" alt="Screenshot 2024-06-20 at 22 46 11" src="https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/753271/971ed338-de1f-46f5-89c9-8121049a78e9">

As I said before, I like to use and adapt the same example in the chapter on transmissions.

**Comment by Ducasse** [comment]
This is a nice idea! Super.
