### ISSUE TITLE
Finish chapter "Integration of Athens in Spec"

### ISSUE THREAD

**Issue by koendehondt** [SquareBracketAssociates/BuildingApplicationWithSpec2#84]
- [ ] Use Alexandrie?
- [x] Check all code examples and images

**Comment by koendehondt** [comment]
@Ducasse

In P13, the example code `AthensHello new openInWindow` fails, similar to https://github.com/pharo-project/pharo/issues/16241. In P13 it works.

<img width="413" alt="Screenshot 2024-06-16 at 22 24 34" src="https://github.com/SquareBracketAssociates/BuildingApplicationWithSpec2/assets/753271/fd52666e-8ec7-4e25-bea8-e6ceb9d81402">

Would it be possible to backport the changes that make it work in P13? Otherwise, we cannot use the example.

Note that this is a reason to use P13, although elsewhere I have suggested not to do that. In fact, this is a bug in P12 that should be fixed.

**Comment by koendehondt** [comment]
@Ducasse In the first section there is a reference to `Balloon Canvas`. What is that?

**Comment by Ducasse** [comment]
BallonCanvas is the default canvas (not cairo) vai a Cplugging  of Pharo and we can remove this reference.
